openapi: 3.0.0
info:
  title: Aplicación de Chat
  description: Este proyecto es una aplicación de chat interactiva desarrollada con React, TypeScript, y Socket.IO
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Local development server 

paths:
components:
  schemas:
  responses:
    